# Generated by Django 3.0.4 on 2020-04-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200330_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Meats on fire', 'Meat on fire'), ('Cheese', 'Cheese'), ('Salads', 'Salads'), ('Eggs', 'Eggs'), ('Vegetables', 'Vegetables'), ('Fish', 'Fish'), ('Milk', 'Milk'), ('DriedFruit', 'DriedFruit'), ('Nuts', 'Nuts'), ('Organic', 'Organic'), ('Milk Delicacies & Yogurt', 'Milk Delicacies & Yogurt'), ('Creamy Margarine Butter', 'Creamy Margarine Butter'), ('Frozen meat', 'Frozen meat'), ('Hot dogs and Sausages', 'Hot dogs and Sausages'), ('Frozen chicken', 'Frozen chicken'), ('Fresh chicken', 'Fresh chicken'), ('Fresh meat', 'Fresh meat'), ('Free and reduced in sugar', 'Free and reduced in sugar'), ('Soy and Lactose free', 'Soy and Lactose free'), ('Gluten free', 'Gluten free'), ('Ice cream and Popsicle', 'Ice cream and Popsicle'), ('Fast food', 'Fast food'), ('Pizzas, Pastries and Dough', 'Pizzas, Pastries and Dough'), ('Vegetarian-ready food', 'Vegetarian-ready food'), ('Frozen vegetables and Fries', 'Frozen vegetables and Fries'), ('Canning', 'Canning'), ('Sauces', 'Sauces'), ('Soups and Stews', 'Soups and Stews'), ('Oil, Vinegar and Lemon juice', 'Oil, Vinegar and Lemon juice'), ('Honey, Jam and Spreads', 'Honey, Jam and Spreads'), ('Spices', 'Spices'), ('Baking products', 'Baking products'), ('Asian cuisine', 'Asian cuisine'), ('Flour and Breadcrumbs', 'Flour and Breadcrumbs'), ('Pasta, Flakes, Couscous', 'Pasta, Flakes, Couscous'), ('Cereals', 'Cereals'), ('Rice and Legumes', 'Rice and Legumes'), ('Sweets', 'Sweets'), ('Salty snacks', 'Salty snacks'), ('Waffles and Biscuits', 'Waffles and Biscuits'), ('Cakes and Cookies', 'Cakes and Cookies'), ('Candy and Gum', 'Candy and Gum'), ('Sweet snacks', 'Sweet snacks'), ('Soft drinks', 'Soft drinks'), ('Hot beverages', 'Hot beverages'), ('Wines', 'Wines'), ('Alcohol and Energy', 'Alcohol and Energy'), ('Concentrations', 'Concentrations'), ('Paper products and Disposable', 'Paper products and Disposable'), ('Covers, Bags and Molds', 'Covers, Bags and Molds'), ('One-time', 'One-time'), ('Picnic', 'Picnic'), ('Candles and Matches', 'Candles and Matches'), ('Housewares', 'Housewares'), ('Home cleaning products', 'Home cleaning products'), ('Dish soaps', 'Dish soaps'), ('Laundry products', 'Laundry products'), ('Cleaning accessories', 'Cleaning accessories'), ('Insecticides and Aerosols', 'Insecticides and Aerosols'), ('Animals products', 'Animals products'), ('Hygiene products', 'Hygiene products'), ('Pharm products', 'Pharm products'), ('Diapers and Wipes', 'Diapers and Wipes'), ('Babies food', 'Babies food'), ('Baby care and Baby accessories', 'Baby care and Baby accessories'), ('Soaps', 'Soaps'), ('Shampoo and Conditioner', 'Shampoo and Conditioner'), ('Deodorant', 'Deodorant'), ('Shaving and Hair removal', 'Shaving and Hair removal'), ('Oral hygiene', 'Oral hygiene'), ('Bread, Pita, Bun', 'Bread, Pita, Bun'), ('Salty pastry', 'Salty pastry')], max_length=60),
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Item')),
            ],
        ),
    ]
