# Generated by Django 3.0.4 on 2020-04-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200402_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=60)),
                ('sub_chain_id', models.CharField(max_length=60)),
                ('store_id', models.CharField(max_length=60)),
                ('store_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sub_stores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.SubStores')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
    ]
