# Generated by Django 3.0.4 on 2020-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_cart_stores_substores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='sub_stores',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='substores',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
