# Generated by Django 3.0.4 on 2020-04-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200403_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='sub_stores',
            new_name='chain_id',
        ),
    ]
